In [1]:
#import Librarys
import numpy as np

In [2]:
# Create an array

a = np.array([[2,3],[4,5]])
a

array([[2, 3],
       [4, 5]])

In [3]:
# Create a Matrix
b = np.matrix([[1,3],[3,5]])
print(b)

[[1 3]
 [3 5]]


In [4]:
# Dot Multiplication===> for this operation we use @.
a@a


array([[16, 21],
       [28, 37]])

In [5]:
print(a@a)

[[16 21]
 [28 37]]


In [6]:
# Other Method
print(np.dot(b,b))

[[10 18]
 [18 34]]


## BradCasting

In [8]:
# just with is this method we can add one number to all of the matrix 
mat = np.array([1,2,3])
mat+5

array([6, 7, 8])

In [11]:
# Ones
c = np.ones([3,3])
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
d = np.array([1,2,3])
new=c+d
new


array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [14]:
new = c*d
new

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [15]:
new = c/d
new

array([[1.        , 0.5       , 0.33333333],
       [1.        , 0.5       , 0.33333333],
       [1.        , 0.5       , 0.33333333]])

In [18]:
g =np.ones([3,1])

In [19]:
g

array([[1.],
       [1.],
       [1.]])

In [20]:
v = np.array([3,4,2])

In [21]:
new = g + v

In [22]:
new

array([[4., 5., 3.],
       [4., 5., 3.],
       [4., 5., 3.]])

In [23]:
new = g * v


In [24]:
new

array([[3., 4., 2.],
       [3., 4., 2.],
       [3., 4., 2.]])

In [26]:
# sum
# sum all of the element
np.sum(new)

27.0

In [27]:
# cumsum
# sum the first element and write in new in firstelement of matrix,sum first and second element and write in 
# second element of new matrix
np.cumsum(new)

array([ 3.,  7.,  9., 12., 16., 18., 21., 25., 27.])

In [31]:
# axis 0,1
# if we add axis value 0, mean it sum the row
# and if value of axis be 1, mean it sum the column
array2 =np.cumsum(new,axis = 0)

In [33]:
array1 =np.cumsum(new,axis=1)

In [35]:
# subtract
subt = np.subtract(array2,array1)
subt

array([[ 0., -3., -7.],
       [ 3.,  1., -5.],
       [ 6.,  5., -3.]])

In [1]:
# devide
devid = np.devide([3,4,5],4)

NameError: name 'np' is not defined