In [42]:
#import Librarys
import numpy as np

In [43]:
# Create an array

a = np.array([[2,3],[4,5]])
a

array([[2, 3],
       [4, 5]])

In [3]:
# Create a Matrix
b = np.matrix([[1,3],[3,5]])
print(b)

[[1 3]
 [3 5]]


In [4]:
# Dot Multiplication===> for this operation we use @.
a@a


array([[16, 21],
       [28, 37]])

In [5]:
print(a@a)

[[16 21]
 [28 37]]


In [6]:
# Other Method
print(np.dot(b,b))

[[10 18]
 [18 34]]


## BradCasting

In [8]:
# just with is this method we can add one number to all of the matrix 
mat = np.array([1,2,3])
mat+5

array([6, 7, 8])

In [11]:
# Ones
c = np.ones([3,3])
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
d = np.array([1,2,3])
new=c+d
new


array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [14]:
new = c*d
new

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [15]:
new = c/d
new

array([[1.        , 0.5       , 0.33333333],
       [1.        , 0.5       , 0.33333333],
       [1.        , 0.5       , 0.33333333]])

In [18]:
g =np.ones([3,1])

In [19]:
g

array([[1.],
       [1.],
       [1.]])

In [20]:
v = np.array([3,4,2])

In [21]:
new = g + v

In [22]:
new

array([[4., 5., 3.],
       [4., 5., 3.],
       [4., 5., 3.]])

In [23]:
new = g * v


In [24]:
new

array([[3., 4., 2.],
       [3., 4., 2.],
       [3., 4., 2.]])

In [26]:
# sum
# sum all of the element
np.sum(new)

27.0

In [27]:
# cumsum
# sum the first element and write in new in firstelement of matrix,sum first and second element and write in 
# second element of new matrix
np.cumsum(new)

array([ 3.,  7.,  9., 12., 16., 18., 21., 25., 27.])

In [31]:
# axis 0,1
# if we add axis value 0, mean it sum the row
# and if value of axis be 1, mean it sum the column
array2 =np.cumsum(new,axis = 0)

In [33]:
array1 =np.cumsum(new,axis=1)

In [35]:
# subtract
subt = np.subtract(array2,array1)
subt

array([[ 0., -3., -7.],
       [ 3.,  1., -5.],
       [ 6.,  5., -3.]])

In [44]:
# devide
devid = np.devide([3,4,5],4)

AttributeError: module 'numpy' has no attribute 'devide'

In [45]:
dev = np.floor_divide([3,4,5],2)

In [46]:
dev

array([1, 2, 2], dtype=int32)

In [47]:
np.math.sqrt(5)

2.23606797749979

In [48]:
np.math.nan

nan

In [49]:
np.math.inf

inf

In [50]:
# Create a random array
np.random.uniform(1,7,(2,3))

array([[5.57488914, 2.01256915, 5.87310298],
       [1.59129313, 2.52242588, 2.81629891]])

In [54]:
# Predic an array
# arange
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [55]:
# Predic an array
# linspace
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [56]:
# Predic an array
my_mask = a>3
a[my_mask]

array([4, 5])

In [63]:
# my_mask2 = np.logical_and(a>3,a<10,)
# my_mask2 = np.logical_not(a>3,a<10,)
# my_mask2 = np.logical_xor(a>3,a<10)
my_mask2 = np.logical_or(a>3,a<10,)

a[my_mask2]

array([2, 3, 4, 5])

In [65]:
# Sppasific array
# Scaler Matrix
np.ones((1,3))

array([[1., 1., 1.]])

In [66]:
# Zero Matrix
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
a

array([[2, 3],
       [4, 5]])

In [69]:
a.dtype

dtype('int32')

In [71]:
# Get the size of array
a.size

4

In [75]:
# Get the Shape of Array
a.shape

(2, 2)

In [85]:
# Get the Unique Value
a = np.array([1,2,3,4,5,6,4,2,4,6,2])

In [77]:
a

array([1, 2, 3, 4, 5, 6, 4, 2, 4, 6, 2])

In [80]:
b= np.unique(a)

In [86]:
a.shape==b.shape

False

In [88]:
# Finde the unity of tow array
# a,b
# union1d
x = np.union1d(a,b)

In [89]:
x

array([1, 2, 3, 4, 5, 6])

In [90]:
# Finde the Junction
# intresect1d
y = np.intersect1d(a,b)

In [91]:
y

array([1, 2, 3, 4, 5, 6])

In [92]:
# Find Mean,Median,Standart Devison,Varians
np.mean(y)

3.5

In [93]:
np.median(y)

3.5

In [94]:
np.std(y)

1.707825127659933

In [95]:
np.var(y)

2.9166666666666665

In [102]:
# Like this x^2+2x+2 = 0
# we have some method in numpy for soliving like this question
coefficient1 = np.array([1,2,2])

In [97]:
np.polyval(coefficient,5)

37

In [105]:
# مشتق گیری
np.polyder(coefficient1)

array([2, 2])

In [106]:
#انتگرال گیری 
np.polyint(coefficient1)# it's mean x^3/3+x^2+2x

array([0.33333333, 1.        , 2.        , 0.        ])